### ISSUE TITLE
lattest saphire error

### ISSUE THREAD

**Issue by 50pips** [project-ecc/Sapphire#103]
Sapphire Auto generated github issue.

STACK TRACE:

TypeError: Cannot read property 'match' of undefined
    at matchName (C:\Program Files\Sapphire\resources\app.asar\node_modules\find-process\lib\find_process.js:18:15)
    at C:\Program Files\Sapphire\resources\app.asar\node_modules\find-process\lib\find_process.js:95:22
    at Array.filter (<anonymous>)
    at ChildProcess.<anonymous> (C:\Program Files\Sapphire\resources\app.asar\node_modules\find-process\lib\find_process.js:91:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

Node Environment: production

Running Environments: 
Sapphire 1.3.0
Electron 6.0.12
win32 10.0.18362
Locale: en-US

**Comment by Dolaned** [comment]
@50pips will look into this, when does this happen for you?

**Comment by 50pips** [comment]
it seems to happen just as coins come out for staking

**Comment by Dolaned** [comment]
fixed https://github.com/project-ecc/sapphire/commit/7a57802bb63e4224c8d2b38b1e3d5bbf8f145915

**Comment by 50pips** [comment]
awesome..well done
