### ISSUE TITLE
Sapphire crashed

### ISSUE THREAD

**Issue by darthlinuxer** [project-ecc/Sapphire#112]
Sapphire Auto generated github issue.

STACK TRACE:

Error: getaddrinfo ENOTFOUND medium.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)

Node Environment: production

Running Environments: 
Sapphire 1.3.0
Electron 6.0.12
win32 10.0.18362
Locale: pt-BR

**Comment by darthlinuxer** [comment]
Unhandled Promise Rejection
NonError: { message: 'Error: getaddrinfo ENOTFOUND api.github.com' }
    at module.exports (C:/Program Files/Sapphire/resources/app.asar/node_modules/ensure-error/index.js:14:10)
    at handleError (C:/Program Files/Sapphire/resources/app.asar/node_modules/electron-unhandled/index.js:24:10)
    at C:/Program Files/Sapphire/resources/app.asar/node_modules/electron-unhandled/index.js:91:4
    at invokeFunc (C:/Program Files/Sapphire/resources/app.asar/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (C:/Program Files/Sapphire/resources/app.asar/node_modules/lodash.debounce/index.js:207:14)
    at timerExpired (C:/Program Files/Sapphire/resources/app.asar/node_modules/lodash.debounce/index.js:195:14)

**Comment by Dolaned** [comment]
https://github.com/project-ecc/sapphire/commit/3320920282afd1bb15559a9d2d3c706f9bc21173
fixed
